format:
  html:
    theme: flatly
project:
  type: website
website:
  navbar:
    background: primary
    right:
    - file: index.qmd
      text: Home
    - file: papers\index.qmd
      text: Papers
    - file: terms\index.qmd
      text: Terms
    search: true
  sidebar:
    collapse-level: 1
    contents:
    - contents:
      - papers\Example.qmd
      section: Papers
    - contents:
      - terms\a.qmd
      section: Terms
    search: true
    style: floating
  title: Example
